name: Build Flutter APK

on:
  push:
    branches: [ main ]
    paths:
      - 'app/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'app/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 'stable'
        channel: 'stable'

    - name: Get dependencies
      working-directory: app
      run: flutter pub get

    - name: Build APK
      working-directory: app
      run: flutter build apk --release

    - name: Get APK path
      id: apk-path
      working-directory: app
      run: echo "path=$(find build/app/outputs/flutter-apk -name '*.apk' | head -1)" >> $GITHUB_OUTPUT

    - name: Send APK to Telegram
      if: github.ref == 'refs/heads/main'
      working-directory: app
      run: |
        APK_PATH="${{ steps.apk-path.outputs.path }}"
        COMMIT_MSG=$(git log -1 --pretty=format:"%s")
        COMMIT_HASH=$(git rev-parse --short HEAD)
        
        curl -F "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
             -F "document=@$APK_PATH" \
             -F "caption=🚀 New Syncure Flutter APK Build
        
        📱 Commit: $COMMIT_MSG
        🔗 Hash: $COMMIT_HASH
        📅 Built: $(date)
        📂 Changes: Flutter App Updated
        
        Download and install to test the latest features!" \
             "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendDocument"

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: syncure-flutter-apk
        path: app/${{ steps.apk-path.outputs.path }}